tasks:
  - before: nvm install 18
    init: pnpm install
    command: pnpm run dev

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
    - heybourn.headwind
    - lokalise.i18n-ally
