image: gitpod/workspace-node

tasks:
  - before: corepack enable
    init: pnpm install
    command: pnpm run dev --host

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
    - heybourn.headwind
    - lokalise.i18n-ally
    - csstools.postcss
