image: gitpod/workspace-node

tasks:
  - before: corepack enable
    init: |
      pnpm install &&
      export HMR_HOST=`gp url 5173`
    command: pnpm run dev

vscode:
  extensions:
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
    - heybourn.headwind
    - lokalise.i18n-ally
