/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as profileNpub1Char123idChar125RouteImport } from './routes/(profile)/npub1{$id}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const profileNpub1Char123idChar125Route =
  profileNpub1Char123idChar125RouteImport.update({
    id: '/(profile)/npub1{$id}',
    path: '/npub1{$id}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/npub1{$id}': typeof profileNpub1Char123idChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/npub1{$id}': typeof profileNpub1Char123idChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(profile)/npub1{$id}': typeof profileNpub1Char123idChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/npub1{$id}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/npub1{$id}'
  id: '__root__' | '/' | '/(profile)/npub1{$id}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  profileNpub1Char123idChar125Route: typeof profileNpub1Char123idChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(profile)/npub1{$id}': {
      id: '/(profile)/npub1{$id}'
      path: '/npub1{$id}'
      fullPath: '/npub1{$id}'
      preLoaderRoute: typeof profileNpub1Char123idChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/(profile)/npub1{$id}' {
  const createFileRoute: CreateFileRoute<
    '/(profile)/npub1{$id}',
    FileRoutesByPath['/(profile)/npub1{$id}']['parentRoute'],
    FileRoutesByPath['/(profile)/npub1{$id}']['id'],
    FileRoutesByPath['/(profile)/npub1{$id}']['path'],
    FileRoutesByPath['/(profile)/npub1{$id}']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  profileNpub1Char123idChar125Route: profileNpub1Char123idChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
