/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appHomeRouteImport } from './routes/(app)/home'
import { Route as appGlobalRouteImport } from './routes/(app)/global'
import { Route as appSettingsRelaysRouteImport } from './routes/(app)/settings/relays'
import { Route as appSettingsGeneralRouteImport } from './routes/(app)/settings/general'
import { Route as apptextnoteNote1Char123idChar125RouteImport } from './routes/(app)/(textnote)/note1{$id}'
import { Route as apptextnoteNevent1Char123idChar125RouteImport } from './routes/(app)/(textnote)/nevent1{$id}'
import { Route as appprofileNpub1Char123idChar125RouteImport } from './routes/(app)/(profile)/npub1{$id}'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appHomeRoute = appHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => appRouteRoute,
} as any)
const appGlobalRoute = appGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRelaysRoute = appSettingsRelaysRouteImport.update({
  id: '/settings/relays',
  path: '/settings/relays',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsGeneralRoute = appSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => appRouteRoute,
} as any)
const apptextnoteNote1Char123idChar125Route =
  apptextnoteNote1Char123idChar125RouteImport.update({
    id: '/(textnote)/note1{$id}',
    path: '/note1{$id}',
    getParentRoute: () => appRouteRoute,
  } as any)
const apptextnoteNevent1Char123idChar125Route =
  apptextnoteNevent1Char123idChar125RouteImport.update({
    id: '/(textnote)/nevent1{$id}',
    path: '/nevent1{$id}',
    getParentRoute: () => appRouteRoute,
  } as any)
const appprofileNpub1Char123idChar125Route =
  appprofileNpub1Char123idChar125RouteImport.update({
    id: '/(profile)/npub1{$id}',
    path: '/npub1{$id}',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof appRouteRouteWithChildren
  '/global': typeof appGlobalRoute
  '/home': typeof appHomeRoute
  '/npub1{$id}': typeof appprofileNpub1Char123idChar125Route
  '/nevent1{$id}': typeof apptextnoteNevent1Char123idChar125Route
  '/note1{$id}': typeof apptextnoteNote1Char123idChar125Route
  '/settings/general': typeof appSettingsGeneralRoute
  '/settings/relays': typeof appSettingsRelaysRoute
}
export interface FileRoutesByTo {
  '/': typeof appRouteRouteWithChildren
  '/global': typeof appGlobalRoute
  '/home': typeof appHomeRoute
  '/npub1{$id}': typeof appprofileNpub1Char123idChar125Route
  '/nevent1{$id}': typeof apptextnoteNevent1Char123idChar125Route
  '/note1{$id}': typeof apptextnoteNote1Char123idChar125Route
  '/settings/general': typeof appSettingsGeneralRoute
  '/settings/relays': typeof appSettingsRelaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/global': typeof appGlobalRoute
  '/(app)/home': typeof appHomeRoute
  '/(app)/(profile)/npub1{$id}': typeof appprofileNpub1Char123idChar125Route
  '/(app)/(textnote)/nevent1{$id}': typeof apptextnoteNevent1Char123idChar125Route
  '/(app)/(textnote)/note1{$id}': typeof apptextnoteNote1Char123idChar125Route
  '/(app)/settings/general': typeof appSettingsGeneralRoute
  '/(app)/settings/relays': typeof appSettingsRelaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/global'
    | '/home'
    | '/npub1{$id}'
    | '/nevent1{$id}'
    | '/note1{$id}'
    | '/settings/general'
    | '/settings/relays'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/global'
    | '/home'
    | '/npub1{$id}'
    | '/nevent1{$id}'
    | '/note1{$id}'
    | '/settings/general'
    | '/settings/relays'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/global'
    | '/(app)/home'
    | '/(app)/(profile)/npub1{$id}'
    | '/(app)/(textnote)/nevent1{$id}'
    | '/(app)/(textnote)/note1{$id}'
    | '/(app)/settings/general'
    | '/(app)/settings/relays'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/global': {
      id: '/(app)/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof appGlobalRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/home': {
      id: '/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof appHomeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(profile)/npub1{$id}': {
      id: '/(app)/(profile)/npub1{$id}'
      path: '/npub1{$id}'
      fullPath: '/npub1{$id}'
      preLoaderRoute: typeof appprofileNpub1Char123idChar125RouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(textnote)/nevent1{$id}': {
      id: '/(app)/(textnote)/nevent1{$id}'
      path: '/nevent1{$id}'
      fullPath: '/nevent1{$id}'
      preLoaderRoute: typeof apptextnoteNevent1Char123idChar125RouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(textnote)/note1{$id}': {
      id: '/(app)/(textnote)/note1{$id}'
      path: '/note1{$id}'
      fullPath: '/note1{$id}'
      preLoaderRoute: typeof apptextnoteNote1Char123idChar125RouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/general': {
      id: '/(app)/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof appSettingsGeneralRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/relays': {
      id: '/(app)/settings/relays'
      path: '/settings/relays'
      fullPath: '/settings/relays'
      preLoaderRoute: typeof appSettingsRelaysRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/(app)/route' {
  const createFileRoute: CreateFileRoute<
    '/(app)',
    FileRoutesByPath['/(app)']['parentRoute'],
    FileRoutesByPath['/(app)']['id'],
    FileRoutesByPath['/(app)']['path'],
    FileRoutesByPath['/(app)']['fullPath']
  >
}
declare module './routes/(app)/global' {
  const createFileRoute: CreateFileRoute<
    '/(app)/global',
    FileRoutesByPath['/(app)/global']['parentRoute'],
    FileRoutesByPath['/(app)/global']['id'],
    FileRoutesByPath['/(app)/global']['path'],
    FileRoutesByPath['/(app)/global']['fullPath']
  >
}
declare module './routes/(app)/home' {
  const createFileRoute: CreateFileRoute<
    '/(app)/home',
    FileRoutesByPath['/(app)/home']['parentRoute'],
    FileRoutesByPath['/(app)/home']['id'],
    FileRoutesByPath['/(app)/home']['path'],
    FileRoutesByPath['/(app)/home']['fullPath']
  >
}
declare module './routes/(app)/(profile)/npub1{$id}' {
  const createFileRoute: CreateFileRoute<
    '/(app)/(profile)/npub1{$id}',
    FileRoutesByPath['/(app)/(profile)/npub1{$id}']['parentRoute'],
    FileRoutesByPath['/(app)/(profile)/npub1{$id}']['id'],
    FileRoutesByPath['/(app)/(profile)/npub1{$id}']['path'],
    FileRoutesByPath['/(app)/(profile)/npub1{$id}']['fullPath']
  >
}
declare module './routes/(app)/(textnote)/nevent1{$id}' {
  const createFileRoute: CreateFileRoute<
    '/(app)/(textnote)/nevent1{$id}',
    FileRoutesByPath['/(app)/(textnote)/nevent1{$id}']['parentRoute'],
    FileRoutesByPath['/(app)/(textnote)/nevent1{$id}']['id'],
    FileRoutesByPath['/(app)/(textnote)/nevent1{$id}']['path'],
    FileRoutesByPath['/(app)/(textnote)/nevent1{$id}']['fullPath']
  >
}
declare module './routes/(app)/(textnote)/note1{$id}' {
  const createFileRoute: CreateFileRoute<
    '/(app)/(textnote)/note1{$id}',
    FileRoutesByPath['/(app)/(textnote)/note1{$id}']['parentRoute'],
    FileRoutesByPath['/(app)/(textnote)/note1{$id}']['id'],
    FileRoutesByPath['/(app)/(textnote)/note1{$id}']['path'],
    FileRoutesByPath['/(app)/(textnote)/note1{$id}']['fullPath']
  >
}
declare module './routes/(app)/settings/general' {
  const createFileRoute: CreateFileRoute<
    '/(app)/settings/general',
    FileRoutesByPath['/(app)/settings/general']['parentRoute'],
    FileRoutesByPath['/(app)/settings/general']['id'],
    FileRoutesByPath['/(app)/settings/general']['path'],
    FileRoutesByPath['/(app)/settings/general']['fullPath']
  >
}
declare module './routes/(app)/settings/relays' {
  const createFileRoute: CreateFileRoute<
    '/(app)/settings/relays',
    FileRoutesByPath['/(app)/settings/relays']['parentRoute'],
    FileRoutesByPath['/(app)/settings/relays']['id'],
    FileRoutesByPath['/(app)/settings/relays']['path'],
    FileRoutesByPath['/(app)/settings/relays']['fullPath']
  >
}

interface appRouteRouteChildren {
  appGlobalRoute: typeof appGlobalRoute
  appHomeRoute: typeof appHomeRoute
  appprofileNpub1Char123idChar125Route: typeof appprofileNpub1Char123idChar125Route
  apptextnoteNevent1Char123idChar125Route: typeof apptextnoteNevent1Char123idChar125Route
  apptextnoteNote1Char123idChar125Route: typeof apptextnoteNote1Char123idChar125Route
  appSettingsGeneralRoute: typeof appSettingsGeneralRoute
  appSettingsRelaysRoute: typeof appSettingsRelaysRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appGlobalRoute: appGlobalRoute,
  appHomeRoute: appHomeRoute,
  appprofileNpub1Char123idChar125Route: appprofileNpub1Char123idChar125Route,
  apptextnoteNevent1Char123idChar125Route:
    apptextnoteNevent1Char123idChar125Route,
  apptextnoteNote1Char123idChar125Route: apptextnoteNote1Char123idChar125Route,
  appSettingsGeneralRoute: appSettingsGeneralRoute,
  appSettingsRelaysRoute: appSettingsRelaysRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
