name: semantic-release
on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # semantic-releaseがbunだけだとバージョンが古くて文句言うので、nodeも入れる
      # https://github.com/semantic-release/semantic-release/pull/2982
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun run semantic-release
